server:
  port: 8765

spring:
  application:
    name: zuul-server
  cloud:
    discovery:
      enabled: true 
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://edueureka.herokuapp.com/eureka/
    fetch-registry: true

management:
  security:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 190000 # Fuse service request timeout

ribbon:
  ReadTimeout: 60000 # Timeout of request processing after connection is established 
  ConnectTimeout: 60000 # Time-out for connection establishment
  MaxAutoRetries: 3 # Number of retries for the current instance
  MaxAutoRetriesNextServer: 3 # Number of retries for switching instances
  eureka:
    enabled: false


zuul:
  routes:
    student-service:
      path: /student-service/**
      serviceId: student-service
    course-service:
      path: /course-service/**
      serviceId: course-service
    notification-service:
      path: /notification-service/**
      serviceId: notification-service
    instructor-service:
      path: /instructor-service/**
      serviceId: instructor-service
      

student-service:
  ribbon:
    listOfServers: edustudent.herokuapp.com
course-service:
  ribbon:
    listOfServers: educourse.herokuapp.com
notification-service:
  ribbon:
    listOfServers: edunotification.herokuapp.com
instructor-service:
  ribbon:
    listOfServers: eduinstructor.herokuapp.com
    
    